version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rag_app
    ports:
      - 8000:8000      
    environment:
      - API_KEY=${API_KEY}
      - HF_TOKEN=${HF_TOKEN}
